name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v3

      - name: Build all targets
        run: bazel build --color=yes --show_progress_rate_limit=30 //...
      
      - name: Test all targets
        run: bazel test --color=yes --test_output=errors --show_progress_rate_limit=30 //...
